### ISSUE TITLE
Set payload equal to error if payload is `instanceof Error`

### ISSUE THREAD

**Issue by danny-andrews** [acdlite/redux-actions#65] opened 2016-02-15 21:25 UTC
I already made a note of this in #43, but I wanted to promote it to its own issue.

I personally think that if you pass an error in as the payload, it should bypass your custom payloadCreator logic and just set the payload equal to the passed-in error. Otherwise, you have to add an error check in each of your action creators to achieve the same effect.
Example:
```js
const createCoolAction = createAction(COOL_ACTION_TYPE, spec => {
  const {zipCode, id} = spec;
  return {body: {zipCode, id}};
});
```
So, if I do something like, `createCoolAction(new Error('Something bad happened'))`, the payload will be set to `{body: {zipCode: undefined, id: undefined}}` instead of just the error object itself. To fix this, I could add an error check, but I don't want to have to do this in every one of my action creators.

I'd be happy to make an MR for this.

**Comment by andrewsuzuki** [comment] 2016-02-16 22:22
I agree. Just made a PR, see #66

**Comment by yangmillstheory** [comment] 2016-07-03 06:56
Wasn't this closed by https://github.com/acdlite/redux-actions/commit/b9d5eb7daec5e29cb02c34dfb855c51183051f71, and a duplicate of https://github.com/acdlite/redux-actions/issues/82?

**Closed** 2016-07-09 09:27 UTC
Labels: help wanted
